export default {
  list: [
    {
      name: 'ZS',
      cnName: '战士',
      maxhp: 32,
      maxsp: 6,
      speed: 1,
      desc: '单体高伤害/控制',
      url: './img/unitzs.png',
      commonSkills: ['C1', 'C2'],
      positiveSkills: ['ZS1'],
      negativeSkills: ['ZS2']
    },
    {
      name: 'LR',
      cnName: '游侠',
      maxhp: 32,
      maxsp: 6,
      speed: 1,
      desc: '群体伤害/控制',
      url: './img/unitlr.png',
      commonSkills: ['C3', 'C4'],
      positiveSkills: ['LR1', 'LR2'],
      negativeSkills: []
    },
    {
      name: 'SM',
      cnName: '萨满',
      maxhp: 32,
      maxsp: 6,
      speed: 1,
      desc: '全体增益效果/反馈伤害',
      url: './img/unitsm.png',
      commonSkills: ['C5', 'C6'],
      positiveSkills: ['SM1'],
      negativeSkills: ['SM2']
    },
    {
      name: 'WS',
      cnName: '武僧',
      maxhp: 33,
      maxsp: 6,
      speed: 1,
      desc: '一击必杀/自我减伤',
      url: './img/unitws.png',
      commonSkills: ['C7', 'C8'],
      positiveSkills: ['WS1'],
      negativeSkills: ['WS2']
    },
    {
      name: 'DZ',
      cnName: '刺客',
      maxhp: 31,
      maxsp: 9,
      speed: 1,
      desc: '高暴击/回能量',
      url: './img/unitdz.png',
      commonSkills: ['C9', 'C10'],
      positiveSkills: ['DZ1'],
      negativeSkills: ['DZ2']
    },
    {
      name: 'FS',
      cnName: '魔法师',
      maxhp: 30,
      maxsp: 6,
      speed: 1,
      desc: '免疫伤害/群体伤害',
      url: './img/unitfs.png',
      commonSkills: ['C11', 'C12'],
      positiveSkills: ['FS1'],
      negativeSkills: ['FS2']
    },
    {
      name: 'XD',
      cnName: '德鲁伊',
      maxhp: 33,
      maxsp: 6,
      speed: 1,
      desc: '变形术/交换生命值',
      url: './img/unitxd.png',
      commonSkills: ['C13', 'C14', 'C15', 'C16', 'C17'],
      positiveSkills: ['XD1', 'XD2', 'XD3', 'XD4'],
      negativeSkills: []
    },
    {
      name: 'DK',
      maxhp: 35,
      maxsp: 6,
      cnName: '死亡骑士',
      speed: 1,
      desc: '吸血/群体伤害',
      url: './img/unitdk.png',
      commonSkills: ['C18', 'C19'],
      positiveSkills: ['DK1'],
      negativeSkills: ['DK2']
    },
    {
      name: 'QS',
      cnName: '圣骑士',
      maxhp: 31,
      maxsp: 6,
      speed: 1,
      desc: '交换生命值/回复生命值',
      url: './img/unitqs.png',
      commonSkills: ['C20', 'C21'],
      positiveSkills: ['QS1', 'QS2'],
      negativeSkills: []
    },
    {
      name: 'MS',
      cnName: '牧师',
      maxhp: 27,
      maxsp: 6,
      speed: 1,
      desc: '回复生命值/全体增益效果',
      url: './img/unitms.png',
      commonSkills: ['C22', 'C23'],
      positiveSkills: ['MS1'],
      negativeSkills: ['MS2']
    },
    {
      name: 'SR',
      cnName: '吟游诗人',
      maxhp: 30,
      maxsp: 6,
      speed: 1,
      desc: '增益效果/减益效果',
      url: './img/unitsr.png',
      commonSkills: ['C24', 'C25'],
      positiveSkills: ['SR1', 'SR2'],
      negativeSkills: []
    },
    {
      name: 'JB',
      cnName: '酒保',
      maxhp: 30,
      maxsp: 6,
      speed: 1,
      desc: '控制/增益效果',
      url: './img/unitjb.png',
      commonSkills: ['C28', 'C29'],
      positiveSkills: ['JB1'],
      negativeSkills: ['JB2']
    },
    {
      name: 'YD',
      cnName: '园丁',
      maxhp: 33,
      maxsp: 0,
      speed: 1,
      desc: '群体伤害/回复效果',
      url: './img/unityd.png',
      commonSkills: ['C30', 'C31'],
      positiveSkills: [],
      negativeSkills: ['YD1', 'YD2']
    },
    {
      name: 'YX',
      cnName: '夜行者',
      maxhp: 32,
      maxsp: 6,
      speed: 3,
      desc: '高速度/多次攻击',
      url: './img/unityx.png',
      commonSkills: ['C32', 'C33'],
      positiveSkills: ['YX1'],
      negativeSkills: ['YX2']
    },
    {
      name: 'TF',
      cnName: '屠夫',
      maxhp: 34,
      maxsp: 6,
      speed: 1,
      desc: '群体伤害/增益效果',
      url: './img/unittf.png',
      commonSkills: ['C34', 'C35'],
      positiveSkills: ['TF1'],
      negativeSkills: ['TF2']
    },
    {
      name: 'PC',
      cnName: '破城者',
      maxhp: 32,
      maxsp: 0,
      speed: 1,
      desc: '高群体伤害',
      url: './img/unitpc.png',
      commonSkills: ['C26', 'C27'],
      positiveSkills: [],
      negativeSkills: ['PC1', 'PC2']
    },
    {
      name: 'MO',
      cnName: '木偶',
      maxhp: 10,
      maxsp: 0,
      speed: 1,
      desc: '伤害加成/高生命值',
      url: './img/unitmo.png',
      commonSkills: ['C36', 'C37'],
      positiveSkills: [],
      negativeSkills: ['MO1', 'MO2']
    }
  ]
}
