export default {
  // NOTE id: C - common, ZS or other hero name - hero skill
  // cat: C - common, P - positive, N - negative
  // type: DA - direct attack, DEF - defence, SK - skill with multiple effects, SA - pure skill attack, SC - pure skill control, BF - buff, DB - debuff
  list: [
    {
      id: 'C1',
      cat: 'C',
      type: 'DA',
      spCost: 0,
      targetLimit: 1,
      cnName: '攻击',
      desc: [],
      detail: '手持宽阔的剑刃斩击敌人，发动一次正常攻击，造成一次直接伤害',
      url: './img/skill_1_zs.png'
    },
    {
      id: 'C2',
      cat: 'C',
      type: 'DEF',
      spCost: 0,
      targetLimit: 0,
      cnName: '守备',
      desc: [],
      detail: '采用防守戒备的行动，可以恢复少量(1)生命值',
      url: './img/skill_2_zs.png'
    },
    {
      id: 'C3',
      cat: 'C',
      type: 'DA',
      spCost: 0,
      targetLimit: 1,
      cnName: '攻击',
      desc: [],
      detail: '挽起弓箭射击敌人，发动一次正常攻击，造成一次直接伤害',
      url: './img/skill_1_lr.png'
    },
    {
      id: 'C4',
      cat: 'C',
      type: 'DEF',
      spCost: 0,
      targetLimit: 0,
      cnName: '守备',
      desc: [],
      detail: '采用防守戒备的行动，可以恢复少量(1)生命值',
      url: './img/skill_2_zs.png'
    },
    {
      id: 'C5',
      cat: 'C',
      type: 'DA',
      spCost: 0,
      targetLimit: 1,
      cnName: '攻击',
      desc: [],
      detail: '挥舞附带元素力量的武器，发动一次正常攻击，造成一次直接伤害',
      url: './img/skill_1_sm.png'
    },
    {
      id: 'C6',
      cat: 'C',
      type: 'DEF',
      spCost: 0,
      targetLimit: 0,
      cnName: '守备',
      desc: [],
      detail: '采用防守戒备的行动，可以恢复少量(1)生命值',
      url: './img/skill_2_zs.png'
    },
    {
      id: 'C7',
      cat: 'C',
      type: 'DA',
      spCost: 0,
      targetLimit: 1,
      cnName: '攻击',
      desc: [],
      detail: '舞动手中的五步棍，发动一次正常攻击，造成一次直接伤害',
      url: './img/skill_1_ws.png'
    },
    {
      id: 'C8',
      cat: 'C',
      type: 'DEF',
      spCost: 0,
      targetLimit: 0,
      cnName: '守备',
      desc: [],
      detail: '采用防守戒备的行动，可以恢复少量(1)生命值',
      url: './img/skill_2_zs.png'
    },
    {
      id: 'C9',
      cat: 'C',
      type: 'DA',
      spCost: 0,
      targetLimit: 1,
      cnName: '攻击',
      desc: [],
      detail: '使用锋利的匕首攻击敌人，发动一次正常攻击，造成一次直接伤害',
      url: './img/skill_1_dz.png'
    },
    {
      id: 'C10',
      cat: 'C',
      type: 'DEF',
      spCost: 0,
      targetLimit: 0,
      cnName: '守备',
      desc: [],
      detail: '采用防守戒备的行动，可以恢复少量(1)生命值',
      url: './img/skill_2_zs.png'
    },
    {
      id: 'C11',
      cat: 'C',
      type: 'DA',
      spCost: 0,
      targetLimit: 1,
      cnName: '攻击',
      desc: [],
      detail: '吟唱寒冷刺骨的魔法，发动一次正常攻击，造成一次直接伤害',
      url: './img/skill_1_fs.png'
    },
    {
      id: 'C12',
      cat: 'C',
      type: 'DEF',
      spCost: 0,
      targetLimit: 0,
      cnName: '守备',
      desc: [],
      detail: '采用防守戒备的行动，可以恢复少量(1)生命值',
      url: './img/skill_2_zs.png'
    },
    {
      id: 'C13',
      cat: 'C',
      type: 'DA',
      spCost: 0,
      targetLimit: 1,
      cnName: '攻击',
      desc: [],
      detail: '借助你的特殊能力，发动一次正常攻击，造成一次直接伤害',
      url: './img/skill_1_xd.png'
    },
    {
      id: 'C14',
      cat: 'C',
      type: 'DA',
      spCost: 0,
      targetLimit: 1,
      cnName: '攻击',
      desc: [],
      detail: '借助你的特殊能力，发动一次正常攻击，造成一次直接伤害',
      url: './img/skill_1_tiger.png'
    },
    {
      id: 'C15',
      cat: 'C',
      type: 'DA',
      spCost: 0,
      targetLimit: 1,
      cnName: '攻击',
      desc: [],
      detail: '借助你的特殊能力，发动一次正常攻击，造成一次直接伤害',
      url: './img/skill_1_bear.png'
    },
    {
      id: 'C16',
      cat: 'C',
      type: 'DA',
      spCost: 0,
      targetLimit: 1,
      cnName: '攻击',
      desc: [],
      detail: '借助你的特殊能力，发动一次正常攻击，造成一次直接伤害',
      url: './img/skill_1_tree.png'
    },
    {
      id: 'C17',
      cat: 'C',
      type: 'DEF',
      spCost: 0,
      targetLimit: 0,
      cnName: '守备',
      desc: [],
      detail: '采用防守戒备的行动，可以恢复少量(1)生命值',
      url: './img/skill_2_zs.png'
    },
    {
      id: 'C18',
      cat: 'C',
      type: 'DA',
      spCost: 0,
      targetLimit: 1,
      cnName: '攻击',
      desc: [],
      detail: '手持你的符文剑，发动一次正常攻击，造成一次直接伤害',
      url: './img/skill_1_dk.png'
    },
    {
      id: 'C19',
      cat: 'C',
      type: 'DEF',
      spCost: 0,
      targetLimit: 0,
      cnName: '守备',
      desc: [],
      detail: '采用防守戒备的行动',
      url: './img/skill_2_zs.png'
    },
    {
      id: 'C20',
      cat: 'C',
      type: 'DA',
      spCost: 0,
      targetLimit: 1,
      cnName: '攻击',
      desc: [],
      detail: '使用正义力量惩戒敌人，发动一次正常攻击，造成一次直接伤害',
      url: './img/skill_1_qs.png'
    },
    {
      id: 'C21',
      cat: 'C',
      type: 'DEF',
      spCost: 0,
      targetLimit: 0,
      cnName: '守备',
      desc: [],
      detail: '采用防守戒备的行动，可以恢复少量(1)生命值',
      url: './img/skill_2_zs.png'
    },
    {
      id: 'C22',
      cat: 'C',
      type: 'DA',
      spCost: 0,
      targetLimit: 1,
      cnName: '攻击',
      desc: [],
      detail: '使用神圣法术惩戒敌人，发动一次正常攻击，造成一次直接伤害',
      url: './img/skill_1_ms.png'
    },
    {
      id: 'C23',
      cat: 'C',
      type: 'DEF',
      spCost: 0,
      targetLimit: 0,
      cnName: '守备',
      desc: [],
      detail: '采用防守戒备的行动，可以恢复少量(1)生命值',
      url: './img/skill_2_zs.png'
    },
    {
      id: 'C24',
      cat: 'C',
      type: 'DA',
      spCost: 0,
      targetLimit: 1,
      cnName: '攻击',
      desc: [],
      detail: '演奏摄人心魄的乐曲，发动一次正常攻击，造成一次直接伤害',
      url: './img/skill_1_sr.png'
    },
    {
      id: 'C25',
      cat: 'C',
      type: 'DEF',
      spCost: 0,
      targetLimit: 0,
      cnName: '守备',
      desc: [],
      detail: '采用防守戒备的行动，可以恢复少量(1)生命值',
      url: './img/skill_2_zs.png'
    },
    {
      id: 'C26',
      cat: 'C',
      type: 'DA',
      spCost: 0,
      targetLimit: 1,
      cnName: '攻击',
      desc: [],
      detail: '挥舞手中沉重的武器，发动一次毁灭性的攻击，造成一次直接伤害',
      url: './img/skill_1_pc.png'
    },
    {
      id: 'C27',
      cat: 'C',
      type: 'DEF',
      spCost: 0,
      targetLimit: 0,
      cnName: '守备',
      desc: [],
      detail: '采用防守戒备的行动，可以恢复少量(1)生命值',
      url: './img/skill_2_zs.png'
    },
    {
      id: 'C28',
      cat: 'C',
      type: 'DA',
      spCost: 0,
      targetLimit: 1,
      cnName: '攻击',
      desc: [],
      detail: '使用手中的戒备棒，发动一次正常攻击，造成一次直接伤害',
      url: './img/skill_1_jb.png'
    },
    {
      id: 'C29',
      cat: 'C',
      type: 'DEF',
      spCost: 0,
      targetLimit: 0,
      cnName: '守备',
      desc: [],
      detail: '采用防守戒备的行动，可以恢复少量(1)生命值',
      url: './img/skill_2_zs.png'
    },
    {
      id: 'C30',
      cat: 'C',
      type: 'DA',
      spCost: 0,
      targetLimit: 1,
      cnName: '攻击',
      desc: [],
      detail: '挥舞手中的花园锄头，不得已地发动一次正常攻击，造成一次直接伤害',
      url: './img/skill_1_yd.png'
    },
    {
      id: 'C31',
      cat: 'C',
      type: 'DEF',
      spCost: 0,
      targetLimit: 0,
      cnName: '守备',
      desc: [],
      detail: '采用防守戒备的行动，可以恢复少量(3)生命值',
      url: './img/skill_2_zs.png'
    },
    {
      id: 'C32',
      cat: 'C',
      type: 'DA',
      spCost: 0,
      targetLimit: 1,
      cnName: '攻击',
      desc: [],
      detail: '手持利刃从阴影中打击敌人，发动一次正常攻击，造成一次直接伤害',
      url: './img/skill_1_yx.png'
    },
    {
      id: 'C33',
      cat: 'C',
      type: 'DEF',
      spCost: 0,
      targetLimit: 0,
      cnName: '守备',
      desc: [],
      detail: '采用防守戒备的行动，可以恢复少量(1)生命值',
      url: './img/skill_2_zs.png'
    },
    {
      id: 'C34',
      cat: 'C',
      type: 'DA',
      spCost: 0,
      targetLimit: 1,
      cnName: '攻击',
      desc: [],
      detail: '高举手中的屠刀，发动一次正常攻击，造成一次直接伤害',
      url: './img/skill_1_tf.png'
    },
    {
      id: 'C35',
      cat: 'C',
      type: 'DEF',
      spCost: 0,
      targetLimit: 0,
      cnName: '守备',
      desc: [],
      detail: '采用防守戒备的行动，可以恢复少量(1)生命值',
      url: './img/skill_2_zs.png'
    },
    {
      id: 'C36',
      cat: 'C',
      type: 'DA',
      spCost: 0,
      targetLimit: 1,
      cnName: '攻击',
      desc: [],
      detail: '发动一次正常攻击，造成一次直接伤害',
      url: './img/skill_1_mo.png'
    },
    {
      id: 'C37',
      cat: 'C',
      type: 'DEF',
      spCost: 0,
      targetLimit: 0,
      cnName: '守备',
      desc: [],
      detail: '采用防守戒备的行动，可以恢复少量(1)生命值',
      url: './img/skill_2_zs.png'
    },
    {
      id: 'ZS1',
      cat: 'P',
      type: 'SK',
      spCost: 3,
      targetLimit: 2,
      cnName: '冲锋',
      desc: [],
      detail: '对一个敌方单位发起冲锋，被冲锋的单位及其相邻的另外一个单位(由你指定)将会被眩晕，并造成少量(2)直接伤害。被眩晕的目标将无法行动！',
      url: './img/skill_3_zs.png'
    },
    {
      id: 'ZS2',
      cat: 'N',
      type: 'BF',
      spCost: 0,
      targetLimit: 0,
      cnName: '鲁莽',
      desc: ['有益效果', '可以驱散'],
      detail: '你的正常攻击造成暴击的话，会获得激怒效果。激怒状态下你的攻击必定暴击，激怒攻击会消耗激怒，激怒攻击本身不触发鲁莽',
      url: './img/skill_5_zs.png'
    },
    {
      id: 'LR1',
      cat: 'P',
      type: 'DA',
      spCost: 3,
      targetLimit: 5,
      cnName: '箭雨',
      desc: [],
      detail: '射出多重箭矢，对所有敌方单位造成直接伤害(不进行攻击程度判定，6点-5伤害/4~5点-3伤害/1~3点-2伤害)',
      url: './img/skill_3_lr.png'
    },
    {
      id: 'LR2',
      cat: 'P',
      type: 'SK',
      spCost: 3,
      targetLimit: 1,
      cnName: '奥术射击',
      desc: [],
      detail: '发动一次普通射击，并使之附带奥术效果。使敌方目标速度降低(速度-2，不叠加)，并能驱散敌方目标身上的激怒或英勇效果',
      url: './img/skill_4_lr.png'
    },
    {
      id: 'SM1',
      cat: 'P',
      type: 'BF',
      spCost: 3,
      targetLimit: 0,
      cnName: '英勇',
      desc: ['有益效果', '可以驱散'],
      detail: '借助元素的力量，鼓舞所有队友。全体友方单位生命值上限提高(2点)，速度上升(2点)，持续2回合，英勇增益效果不会叠加',
      url: './img/skill_3_sm.png'
    },
    {
      id: 'SM2',
      cat: 'N',
      type: 'BF',
      spCost: 0,
      targetLimit: 0,
      cnName: '大地之力',
      desc: ['有益效果', '无法驱散'],
      detail: '召唤大地母亲护佑全体友方单位，持续整场战斗。若敌方对友方单位造成暴击的时候，1/3伤害将反馈给攻击方自行承受',
      url: './img/skill_5_sm.png'
    },
    {
      id: 'WS1',
      cat: 'P',
      type: 'DA',
      spCost: 3,
      targetLimit: 1,
      cnName: '死亡一指',
      desc: [],
      detail: '发动武术绝学，对一名敌方单位发动一次强力的终结技能，造成直接伤害。若目标生命值为10及以下则立即击杀该目标，否则对其造成5点伤害值',
      url: './img/skill_3_ws.png'
    },
    {
      id: 'WS2',
      cat: 'N',
      type: 'BF',
      spCost: 0,
      targetLimit: 0,
      cnName: '醉拳',
      desc: ['有益效果', '无法驱散'],
      detail: '任何对你的直接伤害更难击中你(1~3-偏斜，4~5-正常，6-暴击)',
      url: './img/skill_5_ws.png'
    },
    {
      id: 'DZ1',
      cat: 'P',
      type: 'SK',
      spCost: 3,
      targetLimit: 1,
      cnName: '毒刃',
      desc: ['有害效果', '可以驱散'],
      detail: '对一名敌方单位发动一次普通攻击，并附带中毒效果(持续2回合，最多2层)。中毒的目标每回合结束会受到3点毒药伤害，毒药伤害不会被减伤效果削弱。此外你对中毒目标进行攻击时将更容易对其暴击(5~6-暴击)',
      url: './img/skill_3_dz.png'
    },
    {
      id: 'DZ2',
      cat: 'N',
      type: 'BF',
      spCost: 0,
      targetLimit: 0,
      cnName: '能量控制',
      desc: ['有益效果', '无法驱散'],
      detail: '最大技能点数SP值及其上限提高1点，你每次攻击结束之后有一定几率(1/6)回复1点SP值',
      url: './img/skill_5_dz.png'
    },
    {
      id: 'FS1',
      cat: 'P',
      type: 'BF',
      spCost: 3,
      targetLimit: 0,
      cnName: '寒冰屏障',
      desc: ['有益效果', '无法驱散'],
      detail: '释放一道寒冰屏障保护自己，持续3回合，寒冰屏障存在的时候你免疫任何*直接*伤害。此外在寒冰屏障持续的时候，使用*守 备*技能可以多回复少量(1点)生命值',
      url: './img/skill_3_fs.png'
    },
    {
      id: 'FS2',
      cat: 'N',
      type: 'BF',
      spCost: 0,
      targetLimit: 0,
      cnName: '冰枪术',
      desc: ['有益效果', '无法驱散'],
      detail: '每次普通攻击有一定几率(50%)触发冰枪术，对当前敌方单位及其左右相邻单位造成一次额外的偏斜伤害',
      url: './img/skill_5_fs.png'
    },
    {
      id: 'XD1',
      cat: 'P',
      type: 'SK',
      spCost: 3,
      targetLimit: 0,
      cnName: '变形术:虎形态',
      desc: ['有益效果', '无法驱散'],
      detail: '回复少量(3)生命值并变形成尖牙利齿的虎形态，在该形态下你所有普通攻击将额外造成2点伤害',
      url: './img/skill_7_xd.png'
    },
    {
      id: 'XD2',
      cat: 'P',
      type: 'SK',
      spCost: 3,
      targetLimit: 0,
      cnName: '变形术:熊形态',
      desc: ['有益效果', '无法驱散'],
      detail: '回复少量(3)生命值并变形成厚实坚硬的熊形态，在该形态下你拥有嘲讽技能，强迫敌方单位必须先攻击你。并且你受到的所有的伤害都会略微减少(1点)',
      url: './img/skill_8_xd.png'
    },
    {
      id: 'XD3',
      cat: 'P',
      type: 'SK',
      spCost: 3,
      targetLimit: 0,
      cnName: '变形术:树形态',
      desc: ['有益效果', '无法驱散'],
      detail: '回复少量(3)生命值并变形成自然和谐的树形态，在该形态下每回合结束所有友方单位都会回复少量(1)生命值',
      url: './img/skill_9_xd.png'
    },
    {
      id: 'XD4',
      cat: 'P',
      type: 'SK',
      spCost: 3,
      targetLimit: 1,
      cnName: '共生术',
      desc: [],
      detail: '精通自然之道，使你与一名友方单位交换彼此的当前生命值',
      url: './img/skill_4_xd.png'
    },
    {
      id: 'DK1',
      cat: 'P',
      type: 'SA',
      spCost: 3,
      targetLimit: 1,
      cnName: '牺牲爪牙',
      desc: [],
      detail: '使用你操控死亡的能力，复活一名敌方已死亡的单位为食尸鬼，并牺牲它使其爆炸。食尸鬼爆炸会对其相邻的单位造成3点伤害',
      url: './img/skill_3_dk.png'
    },
    {
      id: 'DK2',
      cat: 'N',
      type: 'BF',
      spCost: 0,
      targetLimit: 0,
      cnName: '邪恶斩击',
      desc: ['有益效果', '无法驱散'],
      detail: '你的正常攻击若造成有效伤害，会使你回复2点生命值，但你的*守 备*动作不会回复生命值',
      url: './img/skill_5_dk.png'
    },
    {
      id: 'QS1',
      cat: 'P',
      type: 'SK',
      spCost: 3,
      targetLimit: 0,
      cnName: '生而平等',
      desc: [],
      detail: '友方生命值最低的单位与敌方生命值最高的单位均分生命值，但不会超过其生命值上限',
      url: './img/skill_3_qs.png'
    },
    {
      id: 'QS2',
      cat: 'P',
      type: 'SK',
      spCost: 6,
      targetLimit: 0,
      cnName: '圣疗术',
      desc: [],
      detail: '祈求圣光照耀，使你的生命值得到完全回复',
      url: './img/skill_4_qs.png'
    },
    {
      id: 'MS1',
      cat: 'P',
      type: 'SK',
      spCost: 3,
      targetLimit: 1,
      cnName: '治疗术',
      desc: [],
      detail: '对一名友方单位进行治疗，并清除目标身上的所有不良效果',
      url: './img/skill_3_ms.png'
    },
    {
      id: 'MS2',
      cat: 'N',
      type: 'BF',
      spCost: 0,
      targetLimit: 0,
      cnName: '强化',
      desc: ['有益效果', '无法驱散'],
      detail: '存活的情况下，所有友方单位最大生命值增加3点。死亡时，回合结束该增益效果自动消失',
      url: './img/skill_5_ms.png'
    },
    {
      id: 'SR1',
      cat: 'P',
      type: 'SK',
      spCost: 4,
      targetLimit: 1,
      cnName: '鼓舞',
      desc: ['有益效果', '无法驱散'],
      detail: '吹奏鼓舞士气的乐曲，使一名友方单位在该场战斗中生命值及其上限永久增加2点，并获得*嘲 讽*技能，强迫敌方单位必须优先攻击他。可以对一名友方单位多次释放该技能，但不能对自己释放',
      url: './img/skill_3_sr.png'
    },
    {
      id: 'SR2',
      cat: 'P',
      type: 'DB',
      spCost: 3,
      targetLimit: 0,
      cnName: '蛊惑曲',
      desc: ['有害效果', '可以驱散'],
      detail: '吹奏蛊惑心智的乐曲，持续2回合，被蛊惑的所有敌方单位有一定(1/3)几率遭受其造成的正常攻击伤害的同等伤害',
      url: './img/skill_4_sr.png'
    },
    {
      id: 'PC1',
      cat: 'N',
      type: 'BF',
      spCost: 0,
      cnName: '横扫',
      targetLimit: 5,
      desc: ['有益效果', '无法驱散'],
      detail: '借助强有力的武器，你的攻击将对所有敌方单位造成同样的伤害，无需指定目标',
      url: './img/skill_5_pc.png'
    },
    {
      id: 'PC2',
      cat: 'N',
      type: 'DB',
      spCost: 0,
      targetLimit: 0,
      cnName: '力量的代价',
      desc: ['有害效果', '无法驱散'],
      detail: '你的攻击不会产生暴击，只会造成偏斜攻击(1~3)或普通攻击(4~6)',
      url: './img/skill_6_pc.png'
    },
    {
      id: 'JB1',
      cat: 'P',
      type: 'DB',
      spCost: 6,
      targetLimit: 1,
      cnName: '醉酒',
      desc: [],
      detail: '灌醉一名敌方单位，使其喝醉。醉酒状态的单位始终跳过其行动回合，醉酒状态在每回合结束有较低概率(1/5)解除',
      url: './img/skill_3_jb.png'
    },
    {
      id: 'JB2',
      cat: 'N',
      type: 'BF',
      spCost: 0,
      targetLimit: 0,
      cnName: '酒壮人胆',
      desc: ['有益效果', '无法驱散'],
      detail: '饮下烈酒，你的攻击伤害值会随着你的生命值的降低而增加(生命值每降低10点，伤害值额外增加1点)',
      url: './img/skill_5_jb.png'
    },
    {
      id: 'YD1',
      cat: 'N',
      type: 'DB',
      spCost: 0,
      targetLimit: 0,
      cnName: '致命藤蔓',
      desc: ['有害效果', '无法驱散'],
      detail: '你存活的回合结束阶段，会召唤出致命的藤蔓攻击所有敌方单位，致命藤蔓每次有一定几率(1/2)对目标造成2点自然伤害。该伤害不会被减伤效果削弱',
      url: './img/skill_5_yd.png'
    },
    {
      id: 'YD2',
      cat: 'N',
      type: 'BF',
      spCost: 0,
      targetLimit: 0,
      cnName: '平和主义',
      desc: ['无法驱散'],
      detail: '你的*守 备*行动回复的生命值额外增加2点，但你的正常攻击始终造成偏斜伤害',
      url: './img/skill_6_yd.png'
    },
    {
      id: 'YX1',
      cat: 'P',
      type: 'DA',
      spCost: 3,
      targetLimit: 1,
      cnName: '幻影打击',
      desc: [],
      detail: '如幻影般的步伐，发动一次正常攻击，幻影打击不会消耗你的行动回合',
      url: './img/skill_3_yx.png'
    },
    {
      id: 'YX2',
      cat: 'N',
      type: 'BF',
      spCost: 0,
      targetLimit: 0,
      cnName: '要害痛击',
      desc: ['有益效果', '无法驱散'],
      detail: '丰富的实战经验使你洞察敌人的弱点，战斗中速度略微增加(2)，你的直接伤害造成暴击的时候，可以额外奖励一个行动回合。幻影打击不触发额外奖励行动回合',
      url: './img/skill_5_yx.png'
    },
    {
      id: 'TF1',
      cat: 'P',
      type: 'SK',
      spCost: 3,
      targetLimit: 1,
      cnName: '行刑',
      desc: [],
      detail: '举起巨大的屠刀对一名敌方单位行刑，发动一次正常攻击。若行刑之后该目标死亡，则其他所有敌方单位都将受到该次伤害的一半顺带伤害。顺带伤害不受免/减伤效果影响',
      url: './img/skill_3_tf.png'
    },
    {
      id: 'TF2',
      cat: 'N',
      type: 'BF',
      spCost: 0,
      targetLimit: 0,
      cnName: '恃强凌弱',
      desc: ['无法驱散'],
      detail: '你对生命值低于10的敌方单位进行攻击时，会额外造成少量(2)伤害。但对生命值为10点及以上的敌方单位进行攻击时，造成的伤害会降低(1)',
      url: './img/skill_5_tf.png'
    },
    {
      id: 'MO1',
      cat: 'N',
      type: 'BF',
      spCost: 0,
      targetLimit: 0,
      cnName: '小不点也有大作为',
      desc: ['有益效果', '无法驱散'],
      detail: '初始伤害固定为1，不进行攻击判定。你的伤害值会随着你的每次攻击而微量增加(1)',
      url: './img/skill_5_mo.png'
    },
    {
      id: 'MO2',
      cat: 'N',
      type: 'BF',
      spCost: 0,
      targetLimit: 0,
      cnName: '玩偶之心',
      desc: ['有益效果', '无法驱散'],
      detail: '初始生命值为10，战斗刚开始时，场上每有一名敌方单位，你的最大生命值增加15；场上每有一名友方单位，你的最大生命值减少5 。你的最大生命值不会低于10点',
      url: './img/skill_6_mo.png'
    }
  ]
}
